name: My_Day_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_picker: ^1.0.11
  date_format: ^2.0.2
  animations: ^2.0.1
  flutter_cupertino_date_picker: ^1.0.0
  http: ^0.13.3
  fluttertoast: ^8.0.8
  dio: any
  keyboard_avoider: ^0.1.2
  numberpicker: ^2.0.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  multi_image_picker: ^4.8.01
  grouped_checkbox: ^1.0.0
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: MyDayIcon
      fonts:
        - asset: fonts/MyDayIcon.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home.png
    - assets/images/home_white.png
    - assets/images/group.png
    - assets/images/group_white.png
    - assets/images/temporary_group.png
    - assets/images/temporary_group_white.png
    - assets/images/study.png
    - assets/images/study_white.png

    - assets/images/search.png
    - assets/images/cancel.png
    - assets/images/confirm.png
    - assets/images/copy.png
    - assets/images/file.png
    - assets/images/setting.png
    - assets/images/friend_choose.png
    - assets/images/group_choose.png
    - assets/images/type.png
    - assets/images/location.png
    - assets/images/schedule.png
    - assets/images/vote.png
    - assets/images/note.png
    - assets/images/share_schedule.png
    - assets/images/share_studyplan.png

    - assets/json/friend_list.json
    - assets/json/best_friend_list.json

    - assets/json/group_list.json
    - assets/json/group_log.json
    - assets/json/group_invite_list.json
    - assets/json/group_member_list.json
    - assets/json/get_group.json

    - assets/json/get_vote.json
    - assets/json/vote_list.json
    - assets/json/vote_end_list.json

    - assets/json/common_note_list.json
    - assets/json/note_list.json
    - assets/json/get_note.json

    - assets/json/common_studyplan_list.json
    - assets/json/personal_share_studyplan_list.json

    - assets/json/common_schedule_list.json
    - assets/json/get_common_schedule.json

    - assets/json/temporary_group_list.json
    - assets/json/temporary_group_invite_list.json
    - assets/json/get_temporary_group_invite.json

    - assets/json/get_studyplan.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
